name: Build And Deploy

on:
  push:
    branches:
      - master
      - node

env:
  GKE_PROJECT: clavision
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-west1-a
  GKE_CLUSTER: example-gke-cluster
  IMAGE: gke-test
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.14"
      - name: npm install
        run: npm install
      - name: Build
        run: npx tsc --project source/tsconfig.json
      - name: Show Files
        run: ls -R
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}
      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      - name: Build the Docker image
        run: |
          docker build -t gcr.io/clavision/main:"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      - name: Push the Docker image to Google Container Registry
        run: docker push gcr.io/clavision/main:$GITHUB_SHA
